bin-y+=fastvideo
fastvideo_SOURCES+=fastvideo.c
fastvideo_SOURCES+=fastvideo_device.c
fastvideo_SOURCES+=spassthrough.c
fastvideo_SOURCES+=daemonize.c
fastvideo_LIBS+=fastvideo
fastvideo_LIBRARY+=jansson
fastvideo_CFLAGS+=-fPIC -rdynamic
fastvideo_LDFLAGS+=-fPIC -rdynamic
